# -*- coding: utf-8 -*-
"""
MLS Optimizer — Patched (colmap v2)
Column mapping (0-based):
  col0: RU (optional)
  col1: EN
  col2: Speaker
  col3: EN-mixed (EN with inline zh/markers)  <-- seed column used by step 20
  col4: ZH_NEW (target)                       <-- all later steps operate here
This file is generated by ChatGPT to fix column layout and pipeline order.
"""

import argparse, json, re, os
import pandas as pd

COL_ZH = 4

ZW_L = "\u2062"
ZW_R = "\u2063"

def unprotect(s: str) -> str:
    if not isinstance(s, str): return s
    return s.replace(ZW_L, "").replace(ZW_R, "")

def load_glossary(glossary_path: str):
    if not os.path.exists(glossary_path): return []
    with open(glossary_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    mapping = {}
    if isinstance(data, dict):
        for k, v in data.items():
            if isinstance(v, str):
                mapping[str(k)] = v
    elif isinstance(data, list):
        for item in data:
            if isinstance(item, dict) and "src" in item and "dst" in item:
                mapping[str(item["src"])] = str(item["dst"])
    items = sorted(mapping.items(), key=lambda kv: len(kv[0]), reverse=True)
    return items

def enforce(text: str, items):
    if not isinstance(text, str) or not text: return text
    # unprotect first (we trust replacements now)
    text = unprotect(text)
    for src, dst in items:
        text = text.replace(src, dst)
    return text

def main():
    ap = argparse.ArgumentParser(description="21_enforce_terms_again: longest-match glossary enforce on col4")
    ap.add_argument("--excel", required=True)
    ap.add_argument("--sheet", default=None)
    ap.add_argument("--glossary", required=True)
    ap.add_argument("--out", default=None)
    args = ap.parse_args()

    df = pd.read_excel(args.excel, sheet_name=args.sheet)
    if df.shape[1] < 5:
        extra = 5 - df.shape[1]
        for _ in range(extra):
            df[df.shape[1]] = ""

    items = load_glossary(args.glossary)

    df.iloc[:, COL_ZH] = df.iloc[:, COL_ZH].map(lambda s: enforce(s, items))
    out = args.out or args.excel
    df.to_excel(out, index=False)
    print(f"[OK] 21_enforce_terms_again done. Output -> {out}")

if __name__ == "__main__":
    main()
