#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
90_release_notes.py — Auto-generate release notes markdown
Inputs: Excel, optional QA report path, glossary path
Output: artifacts/RELEASE_NOTES.md
"""
import argparse, json, datetime
from pathlib import Path
import pandas as pd

ARTI_DIR = Path(__file__).resolve().parent.parent / "artifacts"
ARTI_DIR.mkdir(parents=True, exist_ok=True)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--excel", required=True)
    ap.add_argument("--sheet", default="0")
    ap.add_argument("--qa", default=str(ARTI_DIR/"qa_report.json"))
    ap.add_argument("--glossary", default=None)
    ap.add_argument("--version", default="0.1.0-alpha.1")
    ap.add_argument("--out", default=str(ARTI_DIR/"RELEASE_NOTES.md"))
    args = ap.parse_args()

    df = pd.read_excel(args.excel, sheet_name=args.sheet)
    rows = df.shape[0]
    filled = int(df.iloc[:,4].fillna("").astype(str).str.strip().ne("").sum())
    rate = f"{filled}/{rows} ({filled*100.0/rows:.1f}%)"

    issues = []
    if Path(args.qa).exists():
        try:
            issues = (json.loads(Path(args.qa).read_text("utf-8")) or {}).get("issues", [])
        except Exception:
            issues = []

    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

    md = f"""# MLS Optimizer Release Notes
Version: **{args.version}**  
Date: **{now}**

## Summary
- File: `{args.excel}` (sheet {args.sheet})
- Filled (col5): **{rate}**

## QA
- Issues found: **{len(issues)}**
- Report: `{args.qa}`

## Changes
- Contextual LLM translation with glossary guard (longest-first)
- College-specific style adaptation (campus places)
- Autosave + resumable WAL/Checkpoint (per 12_llm_translate)
- Terms enforcement pass
- QA checks (placeholders/links/numbers/length ratio)
- Stats & Release notes generator

---
Generated by `90_release_notes.py`.
"""
    Path(args.out).write_text(md, encoding="utf-8")
    print(f"[OK] Release notes written -> {args.out}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
